ROOT_DIR := $(realpath $(dir $(realpath $(lastword $(MAKEFILE_LIST)))))

# The project directories are according to the OTP principles
EBIN := ${ROOT_DIR}/ebin
SRC  := ${ROOT_DIR}/src
INCLUDE := ${ROOT_DIR}/include
PRIV := ${ROOT_DIR}/priv
PRIV_BIN := ${PRIV}/bin
PYTHON_SRC := ${ROOT_DIR}/python_src

# OTP Application - Rememeber to bump the version for new releases
APP_NAME := $(notdir $(ROOT_DIR))
APP_VER := 0.0.1

APP_SPEC_SRC := $(SRC)/$(APP_NAME).app.src
APP_SPEC := $(EBIN)/$(APP_NAME).app

# Erlang source code
ERL_FILES := $(shell find $(SRC) -name '*.erl')
BEAM_FILES := $(patsubst %.erl,$(EBIN)/%.beam,$(notdir $(ERL_FILES)))

HRL_DIRS := $(shell find ${SRC} -name '*.hrl')
HRL_DIRS := $(if $(strip $(HRL_DIRS)),\
                 $(shell echo ${HRL_DIRS} | xargs dirname | sort -u),)
ifneq ($(wildcard $(INCLUDE)/*),)
    HRL_DIRS += $(shell find ${INCLUDE} -name '*.hrl' | xargs dirname | sort -u)
endif

# Erlang Compiler
ERLC := erlc

INCLUDE_FLAG := $(addprefix -I ,$(HRL_DIRS))
ERLCFLAGS = $(INCLUDE_FLAG) -MMD -MP

# Libminutia source code
LIBMINUTIA := ${PYTHON_SRC}/libminutia
PY_FILES := $(shell find ${LIBMINUTIA} -name '*.py')
LIBMINUTIA_BUILD := ${PRIV_BIN}/libminutia

# Python
PYTHON := python3


.PHONY: all clean dev


all: $(LIBMINUTIA_BUILD) $(APP_SPEC) $(BEAM_FILES)

dev: clean $(LIBMINUTIA_BUILD) $(APP_SPEC) $(BEAM_FILES)
	mkdir /tmp/hi_minutia_dev                                  \
	&& cd /tmp/hi_minutia_dev                                  \
	&& git clone https://github.com/hyperimpose/miscellany.git \
    && cd miscellany                                           \
    && make SELECT=bencode,polycache
	erl -pz ebin /tmp/hi_minutia_dev/miscellany/ebin \
        -eval 'application:start(bencode).'          \
        -eval 'application:start(polycache).'        \
        -eval 'application:start(minutia).'          \
	&& rm -rf /tmp/hi_minutia_dev


${BEAM_FILES}: ${ERL_FILES} | $(EBIN)
	$(ERLC) $(ERLCFLAGS) -o $(EBIN) -- $?


${APP_SPEC}: ${APP_SPEC_SRC} | $(EBIN)
	sed 's/=version=/${APP_VER}/g' ${APP_SPEC_SRC} > ${APP_SPEC}


# Note: LM_OPTS is for installing optional dependencies for libminutia.
#       It is meant to be specified from the command line when running make.
#       Examples: make LM_OPTS=[explicit,media]
#                 make LM_OPTS=[media]
${LIBMINUTIA_BUILD}: ${PY_FILES} | $(PRIV) $(PRIV_BIN)
	mkdir -p $(LIBMINUTIA_BUILD)
	cp -r ${LIBMINUTIA}/* $(LIBMINUTIA_BUILD)
	cd $(LIBMINUTIA_BUILD) \
	&& $(PYTHON) -m venv venv \
	&& . venv/bin/activate \
	&& $(PYTHON) -m pip install .${LM_OPTS} --target $(LIBMINUTIA_BUILD)


$(EBIN) $(PRIV) $(PRIV_BIN):
	mkdir -p $@


clean:
	rm -rf $(EBIN) $(LIBMINUTIA_BUILD)


# These are generated by the compiler from the MMD and MP options
-include $(BEAM_FILES:.beam=.Pbeam)
