%%--------------------------------------------------------------------
%% Copyright (C) 2023-2024 hyperimpose.org
%%
%% This file is part of minutia.
%%
%% This program is free software: you can redistribute it and/or modify
%% it under the terms of the GNU Affero General Public License as published
%% by the Free Software Foundation, version 3.
%%
%% This program is distributed in the hope that it will be useful,
%% but WITHOUT ANY WARRANTY; without even the implied warranty of
%% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%% GNU Affero General Public License for more details.
%%
%% You should have received a copy of the GNU Affero General Public License
%% along with this program.  If not, see <https://www.gnu.org/licenses/>.
%%--------------------------------------------------------------------

%%%-------------------------------------------------------------------
%%% This module provides functions to convert the output of libminutia
%%% to Erlang friendly representations.
%%%
%%% Specifically the following functions will:
%%% - Convert binary keys to atoms
%%% - Remove keys meant for internal use (_link, _lang, _ttl etc.)
%%% - Use the atoms true, false to represent boolean values
%%%-------------------------------------------------------------------

-module(minutia_response).

-export([http/1]).
-export_types([http/1]).

-define(BOOLEAN(Bin), case Bin of <<"true">> -> true; _Else -> false end).


%%%===================================================================
%%% HTTP
%%%===================================================================

%%% Types ============================================================

-type http() :: http_html()
              | http_fallback()
              | http_lainchan_thread()
              | http_mediainfo_audio()
              | http_mediainfo_image()
              | http_mediainfo_video()
              | http_mupdf()
              | http_nitter()
              | http_png()
              | http_reddit_comments()
              | http_twitter_tweet()
              | http_youtube_search()
              | http_youtube_video().

-type http_html() ::
        #{m        => http_html,
          t        => binary(),   % Title generated by minutia
          explicit => boolean()}.  % Adult content

-type http_fallback() ::
        #{m            => http_fallback,
          t            => binary(),   % Title generated by minutia
          content_type => binary(),   % Content-Type header
          explicit     => boolean(),  % Adult content
          filename     => binary(),   % From Content-Disposition
          size         => binary()}.   % Human readable filesize

-type http_lainchan_thread() ::
        #{m        => http_lainchan_thread,
          t        => binary(),   % Title generated by minutia
          board    => binary(),   % The board of the post
          explicit => boolean(),  % Adult content
          files    => integer(),  % Number of files posted
          post     => binary(),   % The post's content
          replies  => integer(),  % Number of replies in thread
          title    => string()}.   % Thread/post title

-type http_mediainfo_audio() ::
        #{m            => http_mediainfo_audio,
          t            => binary(),   % Title generated by minutia
          album        => binary(),   % From the tags
          artist       => binary(),   % From the tags
          content_type => binary(),   % Content-Type header
          date         => binary(),   % From the tags
          duration     => binary(),   % Human readable: 02:12
          explicit     => boolean(),  % Adult content
          format       => binary(),   % The file format. e.g. MP3
          size         => binary(),   % Human readable filesize
          title        => binary()}.  % From the tags

-type http_mediainfo_image() ::
        #{m            => http_mediainfo_image,
          t            => binary(),    % Title generated by minutia
          content_type => binary(),    % Content-Type header
          explicit     => boolean(),   % Adult content
          format       => binary(),    % The file format. e.g. GIF
          size         => binary(),    % Human readable filesize
          title        => binary(),    % From the tags
          width        => integer(),   % In pixels
          height       => integer()}.  % In pixels

-type http_mediainfo_video() ::
        #{m            => http_mediainfo_video,
          t            => binary(),    % Title generated by minutia
          content_type => binary(),    % Content-Type header
          duration     => binary(),    % Human readable: 01:12:54
          explicit     => boolean(),   % Adult content
          format       => binary(),    % The file format. e.g. MP4
          size         => binary(),    % Human readable filesize
          title        => binary(),    % From the tags
          width        => integer(),   % In pixels
          height       => integer()}.  % In pixels

-type http_mupdf() ::
        #{m            => http_mupdf,
          t            => binary(),   % Title generated by minutia
          content_type => binary(),   % Content-Type header
          explicit     => boolean(),  % Adult content
          pages        => binary(),   % Number of pages in document
          size         => binary(),   % Human readable filesize
          title        => binary()}.  % Document metadata or snippet

-type http_nitter() ::
        #{m            => http_nitter,
          t            => binary(),    % Usually the username
          description  => binary(),    % Usually the tweet
          explicit     => boolean()}.  % Adult content

-type http_png() ::
        #{m        => http_png,
          t        => binary(),    % Title generated by minutia
          explicit => boolean(),   % Adult content
          height   => integer(),   % In pixels
          size     => binary(),    % Human readable filesize
          width    => integer()}.  % In pixels

-type http_reddit_comments() ::
        #{m           => http_reddit_comments,
          t           => binary(), % Title generated by minutia
          title       => binary(),      % Post title
          author_name => binary(),  % Username that made the post / comment
          html        => binary(),
          subreddit   => binary()}.  % The subreddit in which the post was made

-type http_twitter_tweet() ::
        #{m        => http_twitter_tweet,
          t        => binary(),    % Title generated by minutia
          explicit => boolean()}.  % Adult content

-type http_youtube_search() ::
        #{m       => http_youtube_search,
          t       => binary(),  % Title generated by minutia
          results => [#{short_url => binary(),     % youtu.be
                        name      => binary(),     % Video title
                        date      => binary(),     % 2 weeks ago
                        views     => binary(),     % 29.404 views
                        channel   => binary(),     % Channel name
                        duration  => binary(),     % 9:02
                        yt_id     => binary()}]}.  % Video id

-type http_youtube_video() ::
        #{m                => http_youtube_video,
          t                => binary(),   % Title by minutia
          author_name      => binary(),   % Channel name
          author_url       => binary(),   % Link to channel
          height           => integer(),  % In pixels
          width            => integer(),  % In pixels
          html             => binary(),   % HTML embed
          thumbnail_height => integer(),  % In pixels
          thumbnail_width  => integer(),  % In pixels
          thumbnail_url    => binary(),   % Link to thumbnail
          title            => binary(),   % Video title
          type             => binary()}.  % <<"video">> or ???

%%% Function =========================================================

-spec http(In :: map()) -> {ok, http()} | false | {error, Error :: binary()}.

http(#{<<"@">> := <<"false">>}) ->
    false;

http(#{<<"@">> := <<"error">>, <<"t">> := T}) ->
    {error, T};

http(#{<<"@">>        := <<"http:html">>,
       <<"t">>        := T,
       <<"explicit">> := Explicit}) ->
    {ok, #{m        => http_html,
           t        => T,
           explicit => ?BOOLEAN(Explicit)}};

http(#{<<"@">>            := <<"http:fallback">>,
       <<"t">>            := T,
       <<"content_type">> := ContentType,
       <<"explicit">>     := Explicit,
       <<"filename">>     := Filename,
       <<"size">>         := Size}) ->
    {ok, #{m            => http_fallback,
           t            => T,
           content_type => ContentType,
           explicit     => ?BOOLEAN(Explicit),
           filename     => Filename,
           size         => Size}};

http(#{<<"@">>        := <<"http:lainchan:thread">>,
       <<"t">>        := T,
       <<"board">>    := Board,
       <<"explicit">> := Explicit,
       <<"files">>    := Files,
       <<"post">>     := Post,
       <<"replies">>  := Replies,
       <<"title">>    := Title}) ->
    {ok, #{m        => http_lainchan_thread,
           t        => T,
           board    => Board,
           explicit => ?BOOLEAN(Explicit),
           files    => Files,
           post     => Post,
           replies  => Replies,
           title    => Title}};

http(#{<<"@">>            := <<"http:mediainfo:audio">>,
       <<"t">>            := T,
       <<"album">>        := Album,
       <<"artist">>       := Artist,
       <<"content_type">> := ContentType,
       <<"date">>         := Date,
       <<"duration">>     := Duration,
       <<"explicit">>     := Explicit,
       <<"format">>       := Format,
       <<"size">>         := Size,
       <<"title">>        := Title}) ->
    {ok, #{m            => http_mediainfo_audio,
           t            => T,
           album        => Album,
           artist       => Artist,
           content_type => ContentType,
           date         => Date,
           duration     => Duration,
           explicit     => ?BOOLEAN(Explicit),
           format       => Format,
           size         => Size,
           title        => Title}};

http(#{<<"@">>            := <<"http:mediainfo:image">>,
       <<"t">>            := T,
       <<"content_type">> := ContentType,
       <<"explicit">>     := Explicit,
       <<"format">>       := Format,
       <<"size">>         := Size,
       <<"title">>        := Title,
       <<"width">>        := Width,
       <<"height">>       := Height}) ->
    {ok, #{m            => http_mediainfo_image,
           t            => T,
           content_type => ContentType,
           explicit     => ?BOOLEAN(Explicit),
           format       => Format,
           size         => Size,
           title        => Title,
           width        => Width,
           height       => Height}};

http(#{<<"@">>            := <<"http:mediainfo:video">>,
       <<"t">>            := T,
       <<"content_type">> := ContentType,
       <<"duration">>     := Duration,
       <<"explicit">>     := Explicit,
       <<"format">>       := Format,
       <<"size">>         := Size,
       <<"title">>        := Title,
       <<"width">>        := Width,
       <<"height">>       := Height}) ->
    {ok, #{m            => http_mediainfo_video,
           t            => T,
           content_type => ContentType,
           duration     => Duration,
           explicit     => ?BOOLEAN(Explicit),
           format       => Format,
           size         => Size,
           title        => Title,
           width        => Width,
           height       => Height}};

http(#{<<"@">>            := <<"http:mupdf">>,
       <<"t">>            := T,
       <<"content_type">> := ContentType,
       <<"explicit">>     := Explicit,
       <<"pages">>        := Pages,
       <<"size">>         := Size,
       <<"title">>        := Title}) ->
    {ok, #{m            => http_mupdf,
           t            => T,
           content_type => ContentType,
           explicit     => ?BOOLEAN(Explicit),
           pages        => Pages,
           size         => Size,
           title        => Title}};

http(#{<<"@">>           := <<"http:nitter">>,
       <<"t">>           := T,
       <<"description">> := Description,
       <<"explicit">>    := Explicit}) ->
    {ok, #{m            => http_nitter,
           t            => T,
           description  => Description,
           explicit     => ?BOOLEAN(Explicit)}};

http(#{<<"@">>        := <<"http:png">>,
       <<"t">>        := T,
       <<"explicit">> := Explicit,
       <<"height">>   := Height,
       <<"size">>     := Size,
       <<"width">>    := Width}) ->
    {ok, #{m        => http_png,
           t        => T,
           explicit => ?BOOLEAN(Explicit),
           height   => Height,
           size     => Size,
           width    => Width}};

http(#{<<"@">>           := <<"http:reddit:comments">>,
       <<"t">>           := T,
       <<"title">>       := Title,
       <<"author_name">> := AuthorName,
       <<"subreddit">>   := Subreddit}) ->
    {ok, #{m           => http_reddit_comments,
           t           => T,
           title       => Title,
           author_name => AuthorName,
           subreddit   => Subreddit}};

http(#{<<"@">>           := <<"http:twitter:tweet">>,
       <<"t">>           := T,
       <<"explicit">>    := Explicit}) ->
    {ok, #{m        => http_twitter_tweet,
           t        => T,
           explicit => ?BOOLEAN(Explicit)}};

http(#{<<"@">>       := <<"http:youtube:search">>,
       <<"t">>       := T,
       <<"results">> := Results}) ->
    R1 = lists:map(fun (#{<<"short_url">> := ShortUrl,
                          <<"name">> := Name,
                          <<"date">> := Date,
                          <<"views">> := Views,
                          <<"channel">> := Channel,
                          <<"duration">> := Duration,
                          <<"yt_id">> := YtId}) ->
                           #{short_url => ShortUrl,
                             name      => Name,
                             date      => Date,
                             views     => Views,
                             channel   => Channel,
                             duration  => Duration,
                             yt_id     => YtId}
                   end,
                   Results),
    {ok, #{m       => http_youtube_search,
           t       => T,
           results => R1}};

http(#{<<"@">>                := <<"http:youtube:video">>,
       <<"t">>                := T,
       <<"author_name">>      := AuthorName,
       <<"author_url">>       := AuthorUrl,
       <<"height">>           := Height,
       <<"html">>             := Html,
       <<"thumbnail_height">> := ThumbnailHeight,
       <<"thumbnail_url">>    := ThumbnailUrl,
       <<"thumbnail_width">>  := ThumbnailWidth,
       <<"title">>            := Title,
       <<"type">>             := Type,
       <<"width">>            := Width}) ->
    {ok, #{m                => http_youtube_video,
           t                => T,
           author_name      => AuthorName,
           author_url       => AuthorUrl,
           height           => Height,
           html             => Html,
           thumbnail_height => ThumbnailHeight,
           thumbnail_url    => ThumbnailUrl,
           thumbnail_width  => ThumbnailWidth,
           title            => Title,
           type             => Type,
           width            => Width}}.
